---
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8010/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uhbyxer/udemy-spring-cloud
          searchPaths: myLabs/ConfigData
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001

