
---
server:
  port: ${PORT:${SERVER_PORT:0}}

---
spring:
  profiles: sentence
server:
  port: 8020
words: NotApplicable

---
spring:
  profiles: lucky
server:
  port: 8002
words: NotApplicable
management:
  security:
    enabled: false