---
spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/Uhbyxer/udemy-spring-cloud
          searchPaths: myLabs/ConfigData
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001